# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-web-console 0.2.2 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-web-console"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rodrigo Rosenfeld Rosas"]
  s.date = "2013-10-07"
  s.description = "Run any Ruby script from the context of a web request."
  s.email = "rr.rosas@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "app/assets/javascripts/console.js",
    "app/assets/stylesheets/console.css",
    "app/controllers/console_controller.rb",
    "app/views/console/index.html.erb",
    "app/views/layouts/console.html.erb",
    "config/routes.rb",
    "lib/console.rb",
    "lib/rails-web-console.rb"
  ]
  s.homepage = "https://github.com/rosenfeld/rails-web-console"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.2"
  s.summary = "A web console for Rails"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

