source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'railties', '4.1.0.rc1'

gem 'rails-web-console', path: '..'#, require: 'rails_web_console/engine'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring', group: :development
